name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    name: Test (${{ matrix.runs-on }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout root directory
        uses: actions/checkout@v4
        with:
          # Repository with crate in root and crate in subdirectory
          repository: 'mondeja/cucumber-thirtyfour-worlder'
      - name: Contains a line starting with 'version ='
        run: |
          if ! grep -q '^version =' Cargo.toml; then
            echo "Error: Cargo.toml does not contain a line starting with 'version ='" >&2
            exit 1
          fi
      - name: Not contains a line starting with 'foobar ='
        run: |
          if grep -q '^foobar =' Cargo.toml; then
            echo "Error: Cargo.toml contains a line starting with 'foobar ='" >&2
            exit 1
          fi
      - name: Replace line starting with 'version =' with 'foobar = 0.0.0'
        uses: mondeja/starts-with-line-replacer@main
        with:
          file: Cargo.toml
          starts-with: 'version ='
          replace-by: 'foobar = "0.0.0"'
      - name: Contains a line with the content 'foobar = 0.0.0'
        run: |
          if ! grep -q '^foobar = "0.0.0"$' Cargo.toml; then
            echo "Error: Cargo.toml does not contain a line with the content 'foobar = 0.0.0'" >&2
            exit 1
          fi
